require 'sinatra/base'
require_relative './models/player'
require_relative './models/computer'
require_relative './models/game'
require_relative './controllers/application_controller'
require_relative './controllers/singleplayer_controller'
require_relative './controllers/multiplayer_controller'
require_relative './helpers/application_helper'